template_path: CF-CoreResources.yaml
dependencies:
  - {{environment}}/{{region}}/CF-CodeBucket.yaml
hooks:
  before_create:
    - !cmd "echo 'Uploading API gateway swagger specification'"
    - !cmd "(AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text);
             PROJECT_CODE={{project_code}};
             sed -e \"s:___AWS_ACCOUNT___:$AWS_ACCOUNT:g\" resources/api-setup.json | aws s3 cp - s3://gd-${PROJECT_CODE,,}-${AWS_ACCOUNT}-code-bucket/api-setup.json)"
  after_create:
    - !cmd resources/swagger-ui-bucket-create.sh
  before_delete:
    - !cmd resources/swagger-ui-bucket-delete.py
