template_path: CF-CoreResources.yaml
dependencies:
  - {{environment}}/{{region}}/CF-CodeBucket.yaml
parameters:
  APIHash: !file_contents resources/api.sha1
  ManagerHash: !file_contents resources/manager.sha1
  ResponseProcessorHash: !file_contents resources/responseprocessor.sha1
  VulnerabilityWatchHash: !file_contents resources/vulnerabilitywatch.sha1
  CpeSubmitHash: !file_contents resources/cpesubmit.sha1
hooks:
  before_create:
    - !cmd resources/upload-api-spec.sh
    - !cmd resources/build-system-lambdas.sh
  after_create:
    - !cmd rm -f resources/*.sha1
    - !cmd resources/swagger-ui-bucket-create.sh
  before_update:
    - !cmd resources/upload-api-spec.sh
    - !cmd resources/build-system-lambdas.sh
  after_update:
    - !cmd rm -f resources/*.sha1
  before_delete:
    - !cmd resources/swagger-ui-bucket-delete.py
