template_path: CF-ServiceLambdas.yaml
dependencies:
  - {{environment}}/{{region}}/CF-CoreResources.yaml
parameters:
  geoipSHA1: !file_contents resources/geoip.sha1
  recordedfutureSHA1: !file_contents resources/recordedfuture.sha1
  shodanSHA1: !file_contents resources/shodan.sha1
  splunkSHA1: !file_contents resources/splunk.sha1
  tester1SHA1: !file_contents resources/tester1.sha1
  whoisSHA1: !file_contents resources/whois.sha1
hooks:
  before_create:
    - !cmd resources/build-service-lambdas.sh
  after_create:
    - !cmd rm -f resources/*.sha1
  before_update:
    - !cmd resources/build-service-lambdas.sh
  after_update:
    - !cmd rm -f resources/*.sha1
