template_path: CF-ServiceLambdas.yaml
dependencies:
  - {{environment}}/{{region}}/CF-CoreResources.yaml
parameters:
  apivoidSHA1: !file_contents resources/apivoid.sha1
  cmapSHA1: !file_contents resources/cmap.sha1
  nvdSHA1: !file_contents resources/nvd.sha1
  passivetotalSHA1: !file_contents resources/passivetotal.sha1
  recordedfutureSHA1: !file_contents resources/recordedfuture.sha1
  servicenowSHA1: !file_contents resources/servicenow.sha1
  shodanSHA1: !file_contents resources/shodan.sha1
  sucuriSHA1: !file_contents resources/sucuri.sha1
  taniumSHA1: !file_contents resources/tanium.sha1
  trustarSHA1: !file_contents resources/trustar.sha1
  urlhausSHA1: !file_contents resources/urlhaus.sha1
  urlscanioSHA1: !file_contents resources/urlscanio.sha1
  virustotalSHA1: !file_contents resources/virustotal.sha1
  whoisSHA1: !file_contents resources/whois.sha1
  zerobounceSHA1: !file_contents resources/zerobounce.sha1
hooks:
  before_create:
    - !cmd resources/build-service-lambdas.sh
    - !cmd resources/log-group-create.py
  after_create:
    - !cmd rm -f resources/*.sha1
    - !cmd ../containers/golang/build.sh ./test/ testap {{aws_account}}
  before_update:
    - !cmd resources/build-service-lambdas.sh
    - !cmd resources/log-group-create.py
  after_update:
    - !cmd rm -f resources/*.sha1
    - !cmd ../containers/golang/build.sh ./test/ testap {{aws_account}}
