AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the GitHubActionsManagedRunner Service Catalog Product

Parameters:
  ProductVersion:
    Type: String
  RunnerName:
    Type: String
    Default: github-actions-runner
  RunnerLabels:
    Type: String
    Description: Comma separated list of labels to attach to the Runner in addition to the default ones.
  GitHubOrganization:
    Type: String
    Description: The organization containing the repository, ex gdcorp-cp
  GitHubRepository:
    Type: String
    Description: The repository to register the GitHub Actions Runner to. Required when IsOrgRunner is false. Example global-tech-registry-lambdas.
    Default: ''
  IsOrgRunner:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Flag to create org runner with a group instead of repository runner.
  RunnerGroupName:
    Type: String
    AllowedPattern: "^(?!Default$).*$"
    Description: Name of runner group for org runner. Default group is not allowed. Required when IsOrgRunner is true.
  GitHubSecretName:
    Type: String
    Description: "Name of the Secrets Manager secret containing 2 keys:
      1. PAT - personal access token to register GitHub Actions Runner.
      2. WEBHOOK_SECRET - webhook secret for webhook to receive 'Workflow jobs' events."
    Default: /GitHub/GitHub-Actions-Runner-Secret
  ScheduleExpression:
    Type: String
    Description: CRON or Rate Schedule for when to force terminate GitHub runner instances in the stack to avoid more than 24 hrs lifetime of any instance. UTC.
    Default: "rate(30 minutes)"
  RunnerAutoScalingGroupDesiredSize:
    Default: 1
    Description: The desired capacity for the instances in the runner autoscaling group
    Type: Number
  RunnerAutoScalingGroupMaxSize:
    Default: 20
    Description: The maximum number of instances in the runner autoscaling group
    Type: Number
  RunnerAutoScalingGroupMinSize:
    Default: 0
    Description: The minimum number of instances in the runner autoscaling group
    Type: Number
  RunnerAutoScalingGroupWarmPoolSize:
    Default: 1
    Description: The minimum number of instances to keep in the warm pool
    Type: Number
  RunnerAMIId:
    Type: String
    Description: SSM Parameter for GAMI
    Default: /GoldenAMI/gd-amzn2/latest
    AllowedPattern: "/GoldenAMI/.+"
  RunnerInstanceType:
    Description: EC2 instance type for the instances.
    Type: String
    Default: t3.small
  # pull Subnet IDs from SSM Parameter Store
  RunnerAutoScalingGroupSubnets:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Description: SSM parameter referencing the Private subnet IDs
    # use /AdminParams/VPC/DXAPPSubnets for DX subnets
    Default: /AdminParams/VPC/PrivateSubnets
  CustomPreInitData:
    Type: String
    Description: Optional commands to utilize prior to the docker service is started
    Default: echo 'No Custom PreInit Data'
  CustomUserData:
    Type: String
    Description: Custom tools and commands to install on the runner before it completes scale out action
    Default: echo 'No Custom UserData'
  UseCICDRole:
    Type: String
    Description: Specifies if you are using CICDRole. Set this to "true" if you want this runner to be able to access secrets or deploy into your dev/test/prod/etc. accounts.
    Default: false
    AllowedValues:
      - false
      - true
  RunnerVolumeSize:
    Type: Number
    Description: Size of Runner volumes in GB between 10 and 200.
    Default: 20
    MinValue: 10
    MaxValue: 200
  DeviceName:
    Type: String
    Description: Root volume mount device name. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
    Default: /dev/xvda

Resources:
  Instance:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: GitHubActionsManagedRunner
      ProvisioningArtifactName: !Ref ProductVersion
      ProvisionedProductName: !Sub ${RunnerName}-sc-asg
      ProvisioningParameters:
        - Key: RunnerInstanceType
          Value: !Ref RunnerInstanceType
        - Key: RunnerAMIId
          Value: !Ref RunnerAMIId
        - Key: RunnerName
          Value: !Ref RunnerName
        - Key: RunnerLabels
          Value: !Ref RunnerLabels
        - Key: GitHubOrganization
          Value: !Ref GitHubOrganization
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: IsOrgRunner
          Value: !Ref IsOrgRunner
        - Key: RunnerGroupName
          Value: !Ref RunnerGroupName
        - Key: RunnerAutoScalingGroupDesiredSize
          Value: !Ref RunnerAutoScalingGroupDesiredSize
        - Key: RunnerAutoScalingGroupWarmPoolSize
          Value: !Ref RunnerAutoScalingGroupWarmPoolSize
        - Key: GitHubSecretName
          Value: !Ref GitHubSecretName
        - Key: CustomPreInitData
          Value: !Ref CustomPreInitData
        - Key: CustomUserData
          Value: !Ref CustomUserData
        - Key: UseCICDRole
          Value: !Ref UseCICDRole
        - Key: RunnerVolumeSize
          Value: !Ref RunnerVolumeSize
        - Key: RunnerAutoScalingGroupSubnets
          Value: !Join [ ",", !Ref RunnerAutoScalingGroupSubnets ]
        - Key: DeviceName
          Value: !Ref DeviceName
      Tags:
        - Key: doNotShutDown
          Value: false
