[tool.tartufo]
exclude-paths = ".tartufo-excludes"
exclude-signatures = [
"0d87be6673203617696bcbbc34b465cb1e3b4c14d79b9cf180628c1be6a9acca", # Signature for sys_id in THREAT_API.md
"6fe4c4cfb73bc9fbaa56916cdf056921f7d5f8a94b15cc803bbbd0436a17eb2b", # Tested if new Tartufo repo failure is working good by adding a entropy string and deleted it
]
json = false
regex = true
entropy = true
