name: Create Runner
project_code: threatapi-cicd
region: us-west-2
template_path: sc-gha-repo-runner.yaml
stack_name: cicd-runners
parameters:
  ProductVersion: 2.0.0
  RunnerName: github-actions-runner-threat-api
  RunnerLabels: self-hosted, threat-runners
  RunnerAutoScalingGroupDesiredSize: "1"
  RunnerVolumeSize: "20"
  RunnerInstanceType: t3.small
  GitHubOrganization: gdcorp-infosec
  GitHubRepository: threat-api
  GitHubSecretName: /GitHub/Runner-Secrets
  RunnerAutoScalingGroupWarmPoolSize: "2"
  RunnerAutoScalingGroupSubnets: /AdminParams/VPC/DXAPPSubnets
  RunnerGroupName: threat-api-runners
  RunnerAMIId: /GoldenAMI/gd-ubuntu20.04/latest
  DeviceName: /dev/sda1
  UseCICDRole: "true"
  IsOrgRunner: "false"
  CustomUserData: |
    sudo snap install amazon-ssm-agent --classic
    sudo systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service
    sudo snap start amazon-ssm-agent
    sudo apt-get install zip unzip libdigest-sha-perl -qy
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
    source ~/.nvm/nvm.sh
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
