# Using a plain debian GCI (Golden Container Image) instead of alpine-python or debian-python
# To avoid "pycryptodome installation" error while installing libraries from requirements.txt

FROM 764525110978.dkr.ecr.us-west-2.amazonaws.com/debian:11

USER root

WORKDIR /

COPY . .

RUN apt update
RUN yes | apt install python3-pip
RUN pip install --no-cache-dir -r requirements.txt

ADD main.py .
ADD awsconnections.py .
ADD fakelambdastructure.py .

CMD ["python3", "./main.py"]
