AWSTemplateFormatVersion: 2010-09-09
Description: ThreatTools API Service Lambdas

Parameters:
  geoipSHA1:
    Type: String
    Description: SHA1 hash of the geoip lambda source
    Default: ""
  tester1SHA1:
    Type: String
    Description: SHA1 hash of the tester1 lambda source
    Default: ""

Resources:
  geoipLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub gd-threattools-${AWS::AccountId}-code-bucket
        S3Key: !Sub geoip/${geoipSHA1}
      Description: !Sub geoip lambda (${geoipSHA1})
      FunctionName: geoip
      Handler: geoip
      MemorySize: 256
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/threattools-custom-ThreatRole
      Runtime: go1.x
      Timeout: 15

  geoipLambdaPermission:
    DependsOn: geoipLambdaFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:geoip
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  geoipSNSSubscription:
    DependsOn: geoipLambdaFunction
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt geoipLambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  tester1LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub gd-threattools-${AWS::AccountId}-code-bucket
        S3Key: !Sub tester1/${tester1SHA1}
      Description: !Sub tester1 lambda (${tester1SHA1})
      FunctionName: tester1
      Handler: tester1.handler
      MemorySize: 128
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/threattools-custom-ThreatRole
      Runtime: python3.7
      Timeout: 15

  tester1LambdaPermission:
    DependsOn: tester1LambdaFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:tester1
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  tester1SNSSubscription:
    DependsOn: tester1LambdaFunction
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt tester1LambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
