AWSTemplateFormatVersion: 2010-09-09
Description: ThreatTools API Service Lambdas

Parameters:
  geoipSHA1:
    Type: String
    Description: SHA1 hash of the geoip lambda source
    Default: ""
  tester1SHA1:
    Type: String
    Description: SHA1 hash of the tester1 lambda source
    Default: ""
  whoisSHA1:
    Type: String
    Description: SHA1 hash of the whois lambda source
    Default: ""

Resources:
  geoipLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub gd-threattools-${AWS::AccountId}-code-bucket
        S3Key: !Sub geoip/${geoipSHA1}
      Description: !Sub geoip lambda (${geoipSHA1})
      FunctionName: geoip
      Handler: geoip
      MemorySize: 256
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/threattools-custom-ThreatRole
      Runtime: go1.x
      Timeout: 15

  geoipLambdaPermission:
    DependsOn: geoipLambdaFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:geoip
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  geoipSNSSubscription:
    DependsOn: geoipLambdaFunction
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt geoipLambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  geoipLambdaEventInvokeConfig:
    DependsOn: geoipLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: geoip
      Qualifier: $LATEST

  geoipLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/geoip
      Type: String
      Value: '{"supported_ioc_types": ["ip"]}'

  tester1LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub gd-threattools-${AWS::AccountId}-code-bucket
        S3Key: !Sub tester1/${tester1SHA1}
      Description: !Sub tester1 lambda (${tester1SHA1})
      FunctionName: tester1
      Handler: tester1.handler
      MemorySize: 128
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/threattools-custom-ThreatRole
      Runtime: python3.7
      Timeout: 15

  tester1LambdaPermission:
    DependsOn: tester1LambdaFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:tester1
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  tester1SNSSubscription:
    DependsOn: tester1LambdaFunction
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt tester1LambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  tester1LambdaEventInvokeConfig:
    DependsOn: tester1LambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: tester1
      Qualifier: $LATEST

  tester1LambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/tester1
      Type: String
      Value: '{"supported_ioc_types": ["domain", "ip", "unknown"]}'

  whoisLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub gd-threattools-${AWS::AccountId}-code-bucket
        S3Key: !Sub whois/${whoisSHA1}
      Description: !Sub whois lambda (${whoisSHA1})
      FunctionName: whois
      Handler: whois
      MemorySize: 256
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/threattools-custom-ThreatRole
      Runtime: go1.x
      Timeout: 15

  whoisLambdaPermission:
    DependsOn: whoisLambdaFunction
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:whois
      Principal: sns.amazonaws.com
      SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  whoisSNSSubscription:
    DependsOn: whoisLambdaFunction
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt whoisLambdaFunction.Arn
      Protocol: lambda
      TopicArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests

  whoisLambdaEventInvokeConfig:
    DependsOn: whoisLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: whois
      Qualifier: $LATEST

  whoisLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/whois
      Type: String
      Value: '{"supported_ioc_types": ["domain"]}'
