AWSTemplateFormatVersion: 2010-09-09
Description: ThreatTools API Service Lambdas

Parameters:
  DevelopmentTeam:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for team owning the created resources.
    Default: /AdminParams/Team/Name
    AllowedValues:
      - /AdminParams/Team/Name
  DevelopmentEnvironment:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM Parameter for development environment this will live in.
    Default: /AdminParams/Team/Environment
    AllowedValues:
      - /AdminParams/Team/Environment
  geoipSHA1:
    Type: String
    Description: SHA1 hash of the geoip lambda source
    Default: ""
  shodanSHA1:
    Type: String
    Description: SHA1 hash of the shodan lambda source
    Default: ""
  tester1SHA1:
    Type: String
    Description: SHA1 hash of the tester1 lambda source
    Default: ""
  urlhausSHA1:
    Type: String
    Description: SHA1 hash of the urlhaus lambda source
    Default: ""
  whoisSHA1:
    Type: String
    Description: SHA1 hash of the whois lambda source
    Default: ""

Resources:
  geoipLambdaFunction:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.3.0
      ProvisionedProductName: geoipLambdaFunction
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub geoip/${geoipSHA1}
        - Key: Handler
          Value: geoip
        - Key: LambdaName
          Value: geoip
        - Key: LambdaDescription
          Value: !Sub geoip lambda (${geoipSHA1})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: go1.x
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: ThreatRole
      Tags:
        - Key: doNotShutDown
          Value: true

  geoipLambdaPermission:
    DependsOn: geoipLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: LambdaPermission
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: geoipLambdaPermission
      ProvisioningParameters:
        - Key: Action
          Value: lambda:InvokeFunction
        - Key: FunctionName
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:geoip
        - Key: Principal
          Value: sns.amazonaws.com
        - Key: SourceArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
      Tags:
        - Key: doNotShutDown
          Value: true

  geoipSNSSubscription:
    DependsOn: geoipLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNSSubscription
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: geoipSNSSubscription
      ProvisioningParameters:
        - Key: Protocol
          Value: lambda
        - Key: TopicArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
        - Key: Endpoint
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:geoip
        - Key: Region
          Value: !Sub ${AWS::Region}
      Tags:
        - Key: doNotShutDown
          Value: true

  geoipLambdaEventInvokeConfig:
    DependsOn: geoipLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: geoip
      Qualifier: $LATEST

  geoipLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/geoip
      Type: String
      Value: '{"supportedIOCTypes": ["IP"]}'

  shodanLambdaFunction:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.3.0
      ProvisionedProductName: shodanLambdaFunction
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub shodan/${shodanSHA1}
        - Key: Handler
          Value: shodan
        - Key: LambdaName
          Value: shodan
        - Key: LambdaDescription
          Value: !Sub shodan lambda (${shodanSHA1})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: go1.x
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: ThreatRole
      Tags:
        - Key: doNotShutDown
          Value: true

  shodanLambdaPermission:
    DependsOn: shodanLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: LambdaPermission
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: shodanLambdaPermission
      ProvisioningParameters:
        - Key: Action
          Value: lambda:InvokeFunction
        - Key: FunctionName
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:shodan
        - Key: Principal
          Value: sns.amazonaws.com
        - Key: SourceArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
      Tags:
        - Key: doNotShutDown
          Value: true

  shodanSNSSubscription:
    DependsOn: shodanLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNSSubscription
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: shodanSNSSubscription
      ProvisioningParameters:
        - Key: Protocol
          Value: lambda
        - Key: TopicArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
        - Key: Endpoint
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:shodan
        - Key: Region
          Value: !Sub ${AWS::Region}
      Tags:
        - Key: doNotShutDown
          Value: true

  shodanLambdaEventInvokeConfig:
    DependsOn: shodanLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: shodan
      Qualifier: $LATEST

  shodanLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/shodan
      Type: String
      Value: '{"supportedIOCTypes": ["DOMAIN", "IP"]}'

  tester1LambdaFunction:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.3.0
      ProvisionedProductName: tester1LambdaFunction
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub tester1/${tester1SHA1}
        - Key: Handler
          Value: tester1.handler
        - Key: LambdaName
          Value: tester1
        - Key: LambdaDescription
          Value: !Sub tester1 lambda (${tester1SHA1})
        - Key: MemorySize
          Value: 128
        - Key: Runtime
          Value: python3.7
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: ThreatRole
      Tags:
        - Key: doNotShutDown
          Value: true

  tester1LambdaPermission:
    DependsOn: tester1LambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: LambdaPermission
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: tester1LambdaPermission
      ProvisioningParameters:
        - Key: Action
          Value: lambda:InvokeFunction
        - Key: FunctionName
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:tester1
        - Key: Principal
          Value: sns.amazonaws.com
        - Key: SourceArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
      Tags:
        - Key: doNotShutDown
          Value: true

  tester1SNSSubscription:
    DependsOn: tester1LambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNSSubscription
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: tester1SNSSubscription
      ProvisioningParameters:
        - Key: Protocol
          Value: lambda
        - Key: TopicArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
        - Key: Endpoint
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:tester1
        - Key: Region
          Value: !Sub ${AWS::Region}
      Tags:
        - Key: doNotShutDown
          Value: true

  tester1LambdaEventInvokeConfig:
    DependsOn: tester1LambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: tester1
      Qualifier: $LATEST

  tester1LambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/tester1
      Type: String
      Value: '{"supportedIOCTypes": ["DOMAIN", "IP", "UNKNOWN"]}'

  urlhausLambdaFunction:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.3.0
      ProvisionedProductName: urlhausLambdaFunction
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub urlhaus/${urlhausSHA1}
        - Key: Handler
          Value: urlhaus
        - Key: LambdaName
          Value: urlhaus
        - Key: LambdaDescription
          Value: !Sub urlhaus lambda (${urlhausSHA1})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: go1.x
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: ThreatRole
      Tags:
        - Key: doNotShutDown
          Value: true

  urlhausLambdaPermission:
    DependsOn: urlhausLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: LambdaPermission
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: urlhausLambdaPermission
      ProvisioningParameters:
        - Key: Action
          Value: lambda:InvokeFunction
        - Key: FunctionName
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:urlhaus
        - Key: Principal
          Value: sns.amazonaws.com
        - Key: SourceArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
      Tags:
        - Key: doNotShutDown
          Value: true

  urlhausSNSSubscription:
    DependsOn: urlhausLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNSSubscription
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: urlhausSNSSubscription
      ProvisioningParameters:
        - Key: Protocol
          Value: lambda
        - Key: TopicArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
        - Key: Endpoint
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:urlhaus
        - Key: Region
          Value: !Sub ${AWS::Region}
      Tags:
        - Key: doNotShutDown
          Value: true

  urlhausLambdaEventInvokeConfig:
    DependsOn: urlhausLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: urlhaus
      Qualifier: $LATEST

  urlhausLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/urlhaus
      Type: String
      Value: '{"supportedIOCTypes": ["UNKNOWN"]}'

  whoisLambdaFunction:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Lambda
      ProvisioningArtifactName: 2.3.0
      ProvisionedProductName: whoisLambdaFunction
      ProvisioningParameters:
        - Key: S3Bucket
          Value: !Sub gd-${DevelopmentTeam}-${DevelopmentEnvironment}-code-bucket
        - Key: S3Key
          Value: !Sub whois/${whoisSHA1}
        - Key: Handler
          Value: whois
        - Key: LambdaName
          Value: whois
        - Key: LambdaDescription
          Value: !Sub whois lambda (${whoisSHA1})
        - Key: MemorySize
          Value: 256
        - Key: Runtime
          Value: go1.x
        - Key: Timeout
          Value: 15
        - Key: CustomIAMRoleNameSuffix
          Value: ThreatRole
      Tags:
        - Key: doNotShutDown
          Value: true

  whoisLambdaPermission:
    DependsOn: whoisLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: LambdaPermission
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: whoisLambdaPermission
      ProvisioningParameters:
        - Key: Action
          Value: lambda:InvokeFunction
        - Key: FunctionName
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:whois
        - Key: Principal
          Value: sns.amazonaws.com
        - Key: SourceArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
      Tags:
        - Key: doNotShutDown
          Value: true

  whoisSNSSubscription:
    DependsOn: whoisLambdaFunction
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: SNSSubscription
      ProvisioningArtifactName: 1.0.1
      ProvisionedProductName: whoisSNSSubscription
      ProvisioningParameters:
        - Key: Protocol
          Value: lambda
        - Key: TopicArn
          Value: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:JobRequests
        - Key: Endpoint
          Value: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:whois
        - Key: Region
          Value: !Sub ${AWS::Region}
      Tags:
        - Key: doNotShutDown
          Value: true

  whoisLambdaEventInvokeConfig:
    DependsOn: whoisLambdaFunction
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnSuccess:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobResponses
        OnFailure:
          Destination: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:JobFailures
      FunctionName: whois
      Qualifier: $LATEST

  whoisLambdaMetadata:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ThreatTools/Modules/whois
      Type: String
      Value: '{"supportedIOCTypes": ["DOMAIN"]}'
