template_path: "SC-ScheduledStepFunctionLighthouse.yaml"
parameters:
  StateMachineName: "LighthouseVulnerabilityWatch"
  LoggingLevel: "ALL"
  LogExecutionData: "true"
  ScheduleExpression: rate(5 minutes)
