name: ThreatAPI Deployment (PROD)

# Deploys the ThreatAPI main branch to the AWS PROD environment using sceptre.

# This workflow needs to run on a self-hosted runner for the time being,
# because "go get" can't access modules on github.secureserver.net correctly
# when running on a GitHub hosted runner, even when the typical workarounds are
# in place to rewrite URLs from https://github.secureserver.net to
# git@github.secureserver.net and the GOPRIVATE environment variable has been
# set.

# It may be possible to avoid this restriction by reading:
# https://tip.golang.org/cmd/go/#hdr-Remote_import_paths
# and modifying modules that exist on github.secureserver.net by specifying
# ".git" in the import list, since the golang tools don't know that the vcs
# type of github.secureserver.net is "git".

# See: https://github.com/golang/go/issues/38964

on:
  push:
    branches: [ main ] # Trigger workflow on all pushes to main branch
  workflow_dispatch:

jobs:
  deploy_to_prod:
    runs-on: [self-hosted,threat-runners]

    if: github.ref == 'refs/heads/main'
    steps:

      # Get version to reference in CO
      - name: Get version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # Deploy to prod
      - name: Reset gitconfig
        run: |
          rm -f $HOME/.gitconfig

      - name: Add Environmental Vars
        run: |
          echo DEPLOY_ROLE=arn:aws:iam::338932590174:role/GD-AWS-USA-GD-ThreatTools-Prod-Deploy >> $GITHUB_ENV

      - name: Get PAT from ASM
        id: masked-secrets
        run: |
          while [[ -z "$AWS_RESPONSE" ]]
          do
              AWS_RESPONSE=`aws --region=us-west-2 secretsmanager get-secret-value --secret-id=/GitHub/Runner-Secrets`
              sleep 1
          done
          CI_TOKEN=`echo $AWS_RESPONSE | jq -r .SecretString | jq -r .PAT`
          echo "::set-output name=ci-token::$CI_TOKEN"
          echo "::add-mask::$CI_TOKEN"

      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      # Checkout the change-order-action
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          repository: gdcorp-actions/change-order-action
          ref: main
          token: ${{ steps.masked-secrets.outputs.ci-token }}
          path: change-order-action

      # Create Change Order
      - name: Create Change Order
        uses: ./change-order-action
        id: create-co
        with:
          snowUser: ${{ secrets.SNOW_USER }}
          snowPass: ${{ secrets.SNOW_PASS }}
          snowUrl: https://godaddy.service-now.com
          action: create
          owningGroup: ENG-Threat Research
          tag: ${{ steps.get-version.outputs.VERSION }}
          environment: production
          region: us-west-2 # optional, will be appended to description
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          state: InProgress

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-region: us-west-2
          role-to-assume: ${{ env.DEPLOY_ROLE }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip

      - name: Install python and other dependencies
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          SECURESERVER_ACCESS_KEY_GHC_SA: ${{ secrets.SECURESERVER_ACCESS_KEY_GHC_SA }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY_GHC_SA}"

          source venv/bin/activate
          chmod u+x ./getpipconf.sh
          ./getpipconf.sh
          pip install -U -r requirements.txt -r requirements-test.txt

      - name: Setup golang environment
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: '1.17.2'

      - name: Install golang dependencies
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          SECURESERVER_ACCESS_KEY_GHC_SA: ${{ secrets.SECURESERVER_ACCESS_KEY_GHC_SA }}
          GITHUBCLOUD_SSH_PRIVATE_KEY: ${{ secrets.GITHUBCLOUD_SSH_PRIVATE_KEY }}
          GH_ACCESS_TOKEN: ${{ steps.masked-secrets.outputs.ci-token }}
          GOPRIVATE: "github.secureserver.net,github.com/gdcorp-*"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${SECURESERVER_ACCESS_KEY_GHC_SA}"
          ssh-add - <<< "${GITHUBCLOUD_SSH_PRIVATE_KEY}"

          git config --global url.git@github.secureserver.net:.insteadOf https://github.secureserver.net/
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
          go mod tidy

          ssh-agent -k

#      This script automatically updates your sceptre files based on directories in apis/.
#      Note: It's infrastructure on fly and not written back to github
      - name: Run tools/generate_sceptre.py
        run: |
          source venv/bin/activate
          cd tools
          python3 generate_sceptre.py

      - name: Run sceptre
        run: |
          source venv/bin/activate
          cd sceptre
          aws s3 cp templates/SC-ServiceLambdas.yaml s3://gd-threattools-prod-code-bucket/template/SC-ServiceLambdas.yaml --quiet
          sceptre launch -y prod/us-west-2

      - name: Update swagger
        run: |
          source venv/bin/activate
          cd sceptre
          ./resources/swagger-ui-bucket-create.sh

      # Close Change Order
      - name: Close Change Order
        uses: ./change-order-action
        with:
          snowUser: ${{ secrets.SNOW_USER }}
          snowPass: ${{ secrets.SNOW_PASS }}
          snowUrl: https://godaddy.service-now.com
          action: update
          owningGroup: ENG-Threat Research
          tag: ${{ steps.get-version.outputs.VERSION }}
          environment: production
          region: ${{ github.event.inputs.region }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          state: Complete
          id: ${{ steps.create-co.outputs.id }}
