name: Deploy Role secrets automatic sync

# Access key rotation docs at https://github.secureserver.net/appservices/service-catalog-products/blob/master/IAMUser/README.md#access-key-rotation
on:
  #    Runs at 00:00 on Sunday UTC
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  sync-cloudservice-credentials:
    runs-on: [self-hosted,threat-runners]
    steps:
      
      - name: Check out build actions
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: gdcorp-actions/update-cloud-service-credentials
          token: ${{ secrets.REPO_CLONE_TOKEN_SA_PAT }}
          path: update-cloud-service-credentials

      - name: Configure prod credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::338932590174:role/GD-AWS-USA-GD-ThreatTools-Prod-Deploy
          role-duration-seconds: 3600
          aws-region: us-west-2
          role-skip-session-tagging: true

      - name: Update prod secrets
        uses: ./update-cloud-service-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.AWS_SECRETS_SYNC_GH_PAT }}
        with:
          aws-secret-id: /Secrets/IAMUser/GD-AWS-DeployUser-ThreatTools-Prod
          access-key-id-secret-name: PROD_AWS_ACCESS_KEY_ID
          secret-access-key-secret-name: PROD_AWS_SECRET_ACCESS_KEY
          org: gdcorp-infosec
          repository: threat-api
