name: cirrus-scan-zaproxy-dev-private

# Post deployment fuzz testing for our endpoints
# For more information on the implementation refer - https://github.com/gdcorp-appservices/cirrus-scan-zaproxy

on:
  workflow_run:
    workflows:
      - ThreatAPI Deployment (DEV-PRIVATE)
    branches:
      - $default-branch
    types:
      - completed
  push:
    paths:
      - '.github/workflows/zaproxy-dev-private.yml'
  workflow_dispatch:

jobs:
  cirrus-scan-dev:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
    # Only run if previous workflow is successful (e.g., tests are green) or it's another event that qualifies.
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e # v1.5.5
        with:
          aws-access-key-id: ${{ secrets.DEV_PRIVATE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_PRIVATE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::345790377847:role/GD-AWS-USA-GD-ThreatTools-Dev-Private-Deploy
          role-duration-seconds: 7200 # 2 hours

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@b9c809dc38d74cd0fde3c13cc4fe4ac72ebecdae # 2.2.2
        with:
          registries: 672751022979

      - name: Pull latest CirrusScan container image
        run: |
          docker pull 672751022979.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd:latest
      - name: Run CirrusScan checks
        run: |
          docker run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_DEFAULT_REGION \
          -e MAX_PASS=50 \
          -e TASK_LIST='["zaproxy"]' \
          -e GITHUB_URL=${GITHUB_SERVER_URL} \
          -e GITHUB_AUTH=${{ secrets.REPO_CLONE_TOKEN_SA_PAT }} \
          -e GITHUB_REPO=${GITHUB_REPOSITORY} \
          -e GITHUB_COMMIT=${GITHUB_SHA} \
          672751022979.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd
