name: cirrus-scan-zaproxy-dev-private

# Post deployment fuzz testing for our endpoints
# For more information on the implementation refer - https://github.com/gdcorp-appservices/cirrus-scan-zaproxy

on:
  workflow_run:
    workflows:
      - ThreatAPI Deployment (DEV-PRIVATE)
    branches:
      - $default-branch
    types:
      - completed
  push:
    paths:
      - '.github/workflows/zaproxy-dev-private.yml'
  workflow_dispatch:

jobs:
  cirrus-scan-dev:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
    # Only run if previous workflow is successful (e.g., tests are green) or it's another event that qualifies.
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'

    steps:
    
      - name: Add Environmental Vars for Dev-Private
        shell: bash
        run: |
          echo DEPLOY_ROLE=arn:aws:iam::345790377847:role/GD-AWS-USA-GD-ThreatTools-Dev-Private-Deploy >> $GITHUB_ENV
      
      - name: Configure AWS credentials for the DEV-PRIVATE Account
        uses: aws-actions/configure-aws-credentials@cefc5912bc61e2b5a3b049c839fc283c7712d4e0
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE }}
          role-duration-seconds: 1200
          aws-region: us-west-2
          role-skip-session-tagging: true

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.3.4
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@3d4e073ce6a6845ed27b30a0fe05b6e22c80ac6b # 2.2.2
        with:
          registries: 672751022979

      - name: Pull latest CirrusScan container image
        run: |
          docker pull 672751022979.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd:latest
      - name: Run CirrusScan checks
        run: |
          docker run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_DEFAULT_REGION \
          -e MAX_PASS=50 \
          -e TASK_LIST='["zaproxy"]' \
          -e GITHUB_URL=${GITHUB_SERVER_URL} \
          -e GITHUB_AUTH=${{ secrets.REPO_CLONE_TOKEN_SA_PAT }} \
          -e GITHUB_REPO=${GITHUB_REPOSITORY} \
          -e GITHUB_COMMIT=${GITHUB_SHA} \
          672751022979.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd
